# Generated by Django 4.0 on 2023-05-17 21:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e7773e9a-97c0-4021-a0f9-b218b71f2082'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af6ea018-37a8-4593-b080-1ddddf55c1cd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
