# Generated by Django 4.0 on 2023-05-17 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0002_rename_author_id_book_author_alter_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b874b21c-44cf-4290-b383-0d322617400e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('176a7f9d-f39e-4be8-9dee-d3173e19a28c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
