# Generated by Django 4.0 on 2023-05-17 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0003_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('682bc05e-d27c-4c96-95e2-5b6682da0fb6'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92d9b90e-86b4-472a-b3f6-9ca11166adf7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
