# Generated by Django 4.0 on 2023-05-18 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0004_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9394858f-06ca-46b5-8ff2-40a3c6b3766d'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94279342-7f6d-4510-bc1c-238978a6a097'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
