# Generated by Django 4.0 on 2023-05-20 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0006_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('574ff169-a29a-47b9-ac34-bd33b9989303'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29975eaa-d671-4318-a863-b73dbbdc168a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
