# Generated by Django 4.0 on 2023-05-20 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0007_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('99987001-2746-48a9-bad9-ec73f4f70372'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b5cc450-4c25-48f2-a01b-e795cd9dd31a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
