# Generated by Django 4.0 on 2023-05-20 12:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0008_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fff57a49-82c9-4f7d-b298-37b2d6e016b3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b975344d-e636-427a-b6e5-c0f19967df56'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
