# Generated by Django 4.0 on 2023-05-20 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0009_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ebf10f7-f3d8-4da9-8cc5-458b05e034fc'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4bb7477f-1afe-4d69-a20a-e5b4023b0063'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
