# Generated by Django 4.0 on 2023-05-20 13:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0010_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('009af82b-0e7c-43a2-b5c3-d9558215dbee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0088276a-860d-4c13-bdd9-a6d38909a0a4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
