# Generated by Django 4.0 on 2023-05-20 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0011_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f82c22e1-46e9-482e-beeb-4add13571f3b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9977a06b-7614-4ece-80ed-fa04ee970041'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
